добавляе стилі контейнеру
AntOn2415/comand-project-01 pull request #6
Opened 2023-01-19 21:58 UTC by AntOn2415

2023-01-19 23:31 UTC, PavloGPS commented on src/sass/components/_container.scss
>    padding: 0 15px;
Додай медіаправила по зміні падінгів для кожного з девайсів свій

2023-01-19 23:32 UTC, PavloGPS requested changes
медіаправила зміни падінгів при різних брекпойнтах

2023-01-20 05:52 UTC, AntOn2415 commented
Як це переглянути? Де видно до падінги різні?

пт, 20 янв. 2023 г., 01:32 Pavlo Grigoriev ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> медіаправила зміни падінгів при різних брекпойнтах
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AntOn2415/comand-project-01/pull/6#pullrequestreview-1262784311>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3PKCQT5GCMOC6SBI7UM2CDWTHFIHANCNFSM6AAAAAAUA3GJTE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-20 08:41 UTC, PavloGPS approved these changes
good job)

2023-01-20 09:31 UTC, merged